// Tina-OpenClaw Use Cases — All 42 cases data
const SITE = {
  titleZh: 'Tina · 龙虾应用案例',
  titleEn: 'Tina · OpenClaw Use Cases',
  subtitleZh: '探索 OpenClaw 在真实生活中的 42 种应用方式',
  subtitleEn: 'Discover 42 real-world ways people use OpenClaw in daily life',
  sourceUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases'
};

const CATEGORIES = [
  { id: 'all',         zh: '全部',                    en: 'All',                      icon: '✦' },
  { id: 'social',      zh: '社交媒体',                 en: 'Social Media',             icon: '📱' },
  { id: 'creative',    zh: '创意与构建',               en: 'Creative & Building',      icon: '🎨' },
  { id: 'devops',      zh: '基础设施与 DevOps',        en: 'Infrastructure & DevOps',  icon: '⚙️' },
  { id: 'productivity',zh: '生产力工具',               en: 'Productivity',             icon: '⚡' },
  { id: 'research',    zh: '研究与学习',               en: 'Research & Learning',      icon: '🔬' },
  { id: 'finance',     zh: '金融与交易',               en: 'Finance & Trading',        icon: '💹' }
];

const CASES = [
  // ── Social Media ──────────────────────────────────────────────────────────
  {
    id: 'daily-reddit-digest',
    nameZh: '每日 Reddit 精选摘要',
    nameEn: 'Daily Reddit Digest',
    category: 'social',
    descZh: '根据你的偏好，自动汇总你关注的 subreddit 精华内容，每天定时推送摘要。',
    descEn: 'Summarize a curated digest of your favourite subreddits, based on your preferences.',
    skillsZh: ['Reddit MCP', '定时任务调度', '邮件 / 消息推送'],
    skillsEn: ['Reddit MCP', 'Scheduled Tasks', 'Email / Message Push'],
    howToZh: '1. 安装 Reddit MCP 插件\n2. 配置你关注的 subreddit 列表与偏好关键词\n3. 设置每日定时触发（如每天早 8 点）\n4. 指定推送渠道（邮件 / Telegram / Slack）\n5. 每天自动收到精华摘要',
    howToEn: '1. Install Reddit MCP plugin\n2. Configure subreddit list and preference keywords\n3. Set daily scheduled trigger (e.g. 8am)\n4. Specify delivery channel (email/Telegram/Slack)\n5. Receive daily digest automatically',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/daily-reddit-digest.md',
    tags: ['自动化', '内容聚合', '定时任务']
  },
  {
    id: 'daily-youtube-digest',
    nameZh: '每日 YouTube 视频摘要',
    nameEn: 'Daily YouTube Digest',
    category: 'social',
    descZh: '自动获取你订阅频道的最新视频摘要，再也不会错过喜爱创作者的内容。',
    descEn: 'Get daily summaries of new videos from your favorite channels — never miss content from creators you follow.',
    skillsZh: ['YouTube MCP', '定时任务', '摘要生成'],
    skillsEn: ['YouTube MCP', 'Scheduled Tasks', 'Summary Generation'],
    howToZh: '1. 配置 YouTube 频道订阅列表\n2. 设置每日定时抓取新视频\n3. 自动生成视频内容摘要\n4. 推送到你的消息渠道',
    howToEn: '1. Configure YouTube channel subscription list\n2. Set daily scheduled fetch for new videos\n3. Auto-generate video content summaries\n4. Push to your messaging channel',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/daily-youtube-digest.md',
    tags: ['自动化', '视频', '内容摘要']
  },
  {
    id: 'x-account-analysis',
    nameZh: 'X 账号深度分析',
    nameEn: 'X Account Analysis',
    category: 'social',
    descZh: '对你的 X（Twitter）账号进行全面的定性分析，了解内容表现与受众特征。',
    descEn: 'Get a qualitative analysis of your X account.',
    skillsZh: ['X/Twitter MCP', '数据分析', '报告生成'],
    skillsEn: ['X/Twitter MCP', 'Data Analysis', 'Report Generation'],
    howToZh: '1. 连接 X/Twitter MCP\n2. 指定要分析的账号\n3. 运行分析任务（内容风格、互动率、受众画像）\n4. 获取结构化分析报告',
    howToEn: '1. Connect X/Twitter MCP\n2. Specify the account to analyze\n3. Run analysis (content style, engagement rate, audience profile)\n4. Get structured analysis report',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/x-account-analysis.md',
    tags: ['分析', '社交媒体', '数据洞察']
  },
  {
    id: 'multi-source-tech-news-digest',
    nameZh: '多源科技新闻聚合摘要',
    nameEn: 'Multi-Source Tech News Digest',
    category: 'social',
    descZh: '自动聚合 109+ 来源（RSS、Twitter/X、GitHub、网络搜索）的科技新闻，按质量评分筛选推送。',
    descEn: 'Automatically aggregate and deliver quality-scored tech news from 109+ sources via natural language.',
    skillsZh: ['RSS 聚合', 'Web 搜索 MCP', '质量评分算法', '消息推送'],
    skillsEn: ['RSS Aggregation', 'Web Search MCP', 'Quality Scoring', 'Message Push'],
    howToZh: '1. 配置 109+ 新闻源（RSS/Twitter/GitHub）\n2. 设置质量评分规则与关键词过滤\n3. 定时运行聚合任务\n4. 按评分排序后推送精选内容',
    howToEn: '1. Configure 109+ news sources (RSS/Twitter/GitHub)\n2. Set quality scoring rules and keyword filters\n3. Run scheduled aggregation\n4. Push curated content sorted by score',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/multi-source-tech-news-digest.md',
    tags: ['新闻聚合', '多源', '质量评分']
  },
  {
    id: 'x-twitter-automation',
    nameZh: 'X/Twitter 全自动化操作',
    nameEn: 'X/Twitter Automation',
    category: 'social',
    descZh: '通过 TweetClaw 插件，在对话中完成发推、回复、点赞、转发、关注、私信、搜索、数据提取、抽奖等全部操作。',
    descEn: 'Post tweets, reply, like, retweet, follow, DM, search, extract data, run giveaways — all from chat via TweetClaw.',
    skillsZh: ['TweetClaw 插件', 'X/Twitter API', '自动化工作流'],
    skillsEn: ['TweetClaw Plugin', 'X/Twitter API', 'Automation Workflow'],
    howToZh: '1. 安装 TweetClaw 插件\n2. 授权 X/Twitter 账号\n3. 用自然语言描述操作（如"帮我回复最新的 10 条提及"）\n4. 代理自动执行并返回结果',
    howToEn: '1. Install TweetClaw plugin\n2. Authorize X/Twitter account\n3. Describe actions in natural language (e.g. "reply to my latest 10 mentions")\n4. Agent executes and returns results',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/x-twitter-automation.md',
    tags: ['Twitter', '自动化', '社交运营']
  },
  // ── Creative & Building ───────────────────────────────────────────────────
  {
    id: 'overnight-mini-app-builder',
    nameZh: '目标驱动自主任务（夜间迷你应用构建器）',
    nameEn: 'Goal-Driven Autonomous Tasks',
    category: 'creative',
    descZh: '倾倒你的目标想法，让代理自主生成、调度并完成每日任务——包括在夜间悄悄构建惊喜迷你应用。',
    descEn: 'Brain dump your goals and have your agent autonomously generate, schedule, and complete daily tasks — including building surprise mini-apps overnight.',
    skillsZh: ['任务调度', '代码生成', '自主规划', '文件系统 MCP'],
    skillsEn: ['Task Scheduling', 'Code Generation', 'Autonomous Planning', 'Filesystem MCP'],
    howToZh: '1. 向代理描述你的长期目标\n2. 代理自动分解为每日可执行任务\n3. 设置夜间自动运行\n4. 早晨查看代理完成的成果（可能是一个新应用！）',
    howToEn: '1. Describe your long-term goals to the agent\n2. Agent auto-decomposes into daily executable tasks\n3. Set up overnight auto-run\n4. Check results in the morning (might be a new app!)',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/overnight-mini-app-builder.md',
    tags: ['自主代理', '代码生成', '目标管理']
  },
  {
    id: 'youtube-content-pipeline',
    nameZh: 'YouTube 内容创作流水线',
    nameEn: 'YouTube Content Pipeline',
    category: 'creative',
    descZh: '自动化视频创意挖掘、选题研究和内容追踪，为 YouTube 频道运营提供完整的内容生产支持。',
    descEn: 'Automate video idea scouting, research, and tracking for a YouTube channel.',
    skillsZh: ['YouTube MCP', 'Web 搜索', '内容规划', '数据库存储'],
    skillsEn: ['YouTube MCP', 'Web Search', 'Content Planning', 'Database Storage'],
    howToZh: '1. 配置目标频道和竞品频道\n2. 代理自动挖掘热门选题\n3. 对每个选题进行深度研究\n4. 将创意和研究结果存入内容数据库\n5. 定期生成内容日历',
    howToEn: '1. Configure target and competitor channels\n2. Agent auto-scouts trending topics\n3. Deep research on each topic\n4. Store ideas and research in content database\n5. Periodically generate content calendar',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/youtube-content-pipeline.md',
    tags: ['YouTube', '内容创作', '自动化']
  },
  {
    id: 'content-factory',
    nameZh: '多智能体内容工厂',
    nameEn: 'Multi-Agent Content Factory',
    category: 'creative',
    descZh: '在 Discord 中运行多智能体内容流水线——研究、写作、缩略图代理各司其职，在专属频道协同工作。',
    descEn: 'Run a multi-agent content pipeline in Discord — research, writing, and thumbnail agents working in dedicated channels.',
    skillsZh: ['Discord MCP', '多智能体协作', '图像生成', '内容写作'],
    skillsEn: ['Discord MCP', 'Multi-Agent Collaboration', 'Image Generation', 'Content Writing'],
    howToZh: '1. 在 Discord 创建专属频道（研究/写作/缩略图）\n2. 为每个频道配置专属代理\n3. 在主频道发布内容需求\n4. 各代理自动协作完成内容生产\n5. 最终输出完整的发布就绪内容',
    howToEn: '1. Create dedicated Discord channels (research/writing/thumbnail)\n2. Configure specialized agents for each channel\n3. Post content requirements in main channel\n4. Agents collaborate automatically\n5. Output publish-ready content',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/content-factory.md',
    tags: ['多智能体', 'Discord', '内容生产']
  },
  {
    id: 'autonomous-game-dev-pipeline',
    nameZh: '自主游戏开发流水线',
    nameEn: 'Autonomous Game Dev Pipeline',
    category: 'creative',
    descZh: '教育游戏开发的全生命周期管理：从待办选择到实现、注册、文档和 Git 提交，强制执行"Bug 优先"策略。',
    descEn: 'Full lifecycle management of educational game development: backlog to implementation, registration, documentation, and git commit. Enforces "Bugs First" policy.',
    skillsZh: ['Git MCP', '代码生成', '文档生成', '任务管理'],
    skillsEn: ['Git MCP', 'Code Generation', 'Documentation', 'Task Management'],
    howToZh: '1. 维护游戏功能待办列表\n2. 代理自动选择优先级最高的任务（Bug 优先）\n3. 自主实现功能并编写文档\n4. 自动提交 Git 并更新注册表\n5. 循环执行直到待办清空',
    howToEn: '1. Maintain game feature backlog\n2. Agent auto-selects highest priority task (Bugs First)\n3. Autonomously implement and document\n4. Auto-commit to Git and update registry\n5. Loop until backlog is empty',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/autonomous-game-dev-pipeline.md',
    tags: ['游戏开发', '自主代理', 'Git']
  },
  {
    id: 'podcast-production-pipeline',
    nameZh: '播客制作全流程自动化',
    nameEn: 'Podcast Production Pipeline',
    category: 'creative',
    descZh: '自动化完整播客工作流——嘉宾研究、节目大纲、节目说明和社交媒体推广，从选题到发布就绪资产一键完成。',
    descEn: 'Automate the full podcast workflow — guest research, episode outlines, show notes, and social media promo — from topic to publish-ready assets.',
    skillsZh: ['Web 搜索 MCP', '文档生成', '社交媒体 MCP', '内容写作'],
    skillsEn: ['Web Search MCP', 'Document Generation', 'Social Media MCP', 'Content Writing'],
    howToZh: '1. 输入播客主题和嘉宾信息\n2. 代理自动研究嘉宾背景\n3. 生成节目大纲和问题列表\n4. 录制后自动生成节目说明\n5. 生成多平台社交媒体推广文案',
    howToEn: '1. Input podcast topic and guest info\n2. Agent auto-researches guest background\n3. Generate episode outline and question list\n4. Auto-generate show notes after recording\n5. Create multi-platform social media promo copy',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/podcast-production-pipeline.md',
    tags: ['播客', '内容创作', '自动化']
  },
  {
    id: 'ai-video-editing',
    nameZh: '对话式 AI 视频剪辑',
    nameEn: 'AI Video Editing via Chat',
    category: 'creative',
    descZh: '用自然语言描述剪辑需求——裁剪、合并、添加音乐、字幕、调色、竖版裁切，无需时间轴，无需 GUI。',
    descEn: 'Edit videos by describing changes in natural language — trim, merge, add music, subtitles, color grade, crop to vertical. No timeline, no GUI.',
    skillsZh: ['FFmpeg MCP', '视频处理', '字幕生成', '自然语言理解'],
    skillsEn: ['FFmpeg MCP', 'Video Processing', 'Subtitle Generation', 'NLU'],
    howToZh: '1. 上传视频文件\n2. 用自然语言描述剪辑需求（如"剪掉前 10 秒，加上字幕"）\n3. 代理调用 FFmpeg 执行操作\n4. 预览并迭代调整\n5. 导出最终视频',
    howToEn: '1. Upload video file\n2. Describe editing needs in natural language (e.g. "cut first 10s, add subtitles")\n3. Agent calls FFmpeg to execute\n4. Preview and iterate\n5. Export final video',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/ai-video-editing.md',
    tags: ['视频剪辑', 'FFmpeg', '自然语言']
  },
  // ── Infrastructure & DevOps ───────────────────────────────────────────────
  {
    id: 'n8n-workflow-orchestration',
    nameZh: 'n8n 工作流编排',
    nameEn: 'n8n Workflow Orchestration',
    category: 'devops',
    descZh: '通过 Webhook 将 API 调用委托给 n8n 工作流——代理永远不接触凭证，每个集成都可视化且可锁定。',
    descEn: 'Delegate API calls to n8n workflows via webhooks — the agent never touches credentials, and every integration is visual and lockable.',
    skillsZh: ['n8n', 'Webhook', 'API 集成', '凭证管理'],
    skillsEn: ['n8n', 'Webhook', 'API Integration', 'Credential Management'],
    howToZh: '1. 在 n8n 中创建工作流并暴露 Webhook\n2. 在 OpenClaw 中配置 Webhook URL\n3. 代理通过自然语言触发工作流\n4. n8n 处理实际 API 调用（凭证安全隔离）\n5. 结果返回给代理',
    howToEn: '1. Create n8n workflow and expose Webhook\n2. Configure Webhook URL in OpenClaw\n3. Agent triggers workflow via natural language\n4. n8n handles actual API calls (credentials isolated)\n5. Results returned to agent',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/n8n-workflow-orchestration.md',
    tags: ['n8n', '工作流', '安全集成']
  },
  {
    id: 'self-healing-home-server',
    nameZh: '自愈家庭服务器',
    nameEn: 'Self-Healing Home Server',
    category: 'devops',
    descZh: '运行一个始终在线的基础设施代理，具备 SSH 访问、自动化 Cron 任务和跨家庭网络的自愈能力。',
    descEn: 'Run an always-on infrastructure agent with SSH access, automated cron jobs, and self-healing capabilities across your home network.',
    skillsZh: ['SSH MCP', 'Cron 调度', '系统监控', '自动修复'],
    skillsEn: ['SSH MCP', 'Cron Scheduling', 'System Monitoring', 'Auto-Repair'],
    howToZh: '1. 配置 SSH MCP 连接家庭服务器\n2. 设置监控 Cron 任务（磁盘、内存、服务状态）\n3. 定义自愈规则（服务崩溃自动重启等）\n4. 代理持续监控并自动修复问题\n5. 异常时发送告警通知',
    howToEn: '1. Configure SSH MCP to connect home server\n2. Set up monitoring cron jobs (disk, memory, service status)\n3. Define self-healing rules (auto-restart on crash, etc.)\n4. Agent continuously monitors and auto-repairs\n5. Send alerts on anomalies',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/self-healing-home-server.md',
    tags: ['服务器', '自动化运维', '自愈']
  },
  // ── Productivity ──────────────────────────────────────────────────────────
  {
    id: 'autonomous-project-management',
    nameZh: '自主项目管理',
    nameEn: 'Autonomous Project Management',
    category: 'productivity',
    descZh: '使用 STATE.yaml 模式协调多智能体项目——子代理并行工作，无需编排器开销。',
    descEn: 'Coordinate multi-agent projects using STATE.yaml pattern — subagents work in parallel without orchestrator overhead.',
    skillsZh: ['多智能体协作', 'YAML 状态管理', '并行任务', '文件系统 MCP'],
    skillsEn: ['Multi-Agent Collaboration', 'YAML State Management', 'Parallel Tasks', 'Filesystem MCP'],
    howToZh: '1. 创建 STATE.yaml 定义项目状态和任务\n2. 启动多个专业子代理\n3. 各代理读取状态文件并认领任务\n4. 并行执行，完成后更新状态\n5. 主代理汇总进度',
    howToEn: '1. Create STATE.yaml defining project state and tasks\n2. Launch multiple specialized subagents\n3. Each agent reads state file and claims tasks\n4. Execute in parallel, update state on completion\n5. Main agent aggregates progress',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/autonomous-project-management.md',
    tags: ['项目管理', '多智能体', '并行']
  },
  {
    id: 'multi-channel-customer-service',
    nameZh: '多渠道 AI 客服系统',
    nameEn: 'Multi-Channel AI Customer Service',
    category: 'productivity',
    descZh: '将 WhatsApp、Instagram、邮件和 Google 评论统一到一个 AI 驱动的收件箱，实现 24/7 自动回复。',
    descEn: 'Unify WhatsApp, Instagram, Email, and Google Reviews in one AI-powered inbox with 24/7 auto-responses.',
    skillsZh: ['WhatsApp MCP', 'Instagram MCP', '邮件 MCP', 'Google 评论 MCP'],
    skillsEn: ['WhatsApp MCP', 'Instagram MCP', 'Email MCP', 'Google Reviews MCP'],
    howToZh: '1. 连接所有消息渠道 MCP\n2. 配置品牌语调和常见问题知识库\n3. 设置自动回复规则和升级策略\n4. 代理 24/7 监控并自动回复\n5. 复杂问题转人工处理',
    howToEn: '1. Connect all messaging channel MCPs\n2. Configure brand tone and FAQ knowledge base\n3. Set auto-reply rules and escalation policy\n4. Agent monitors and auto-replies 24/7\n5. Escalate complex issues to human',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/multi-channel-customer-service.md',
    tags: ['客服', '多渠道', '自动化']
  },
  {
    id: 'phone-based-personal-assistant',
    nameZh: '电话个人助手',
    nameEn: 'Phone-Based Personal Assistant',
    category: 'productivity',
    descZh: '通过电话访问你的 AI 代理，免提语音助手支持任何手机，随时获取日历、Jira 工单和网络搜索结果。',
    descEn: 'Access OpenClaw from any phone via voice call or SMS. Get calendar updates, Jira tickets, and web search results hands-free.',
    skillsZh: ['Twilio MCP', '语音识别', '日历 MCP', 'Jira MCP'],
    skillsEn: ['Twilio MCP', 'Speech Recognition', 'Calendar MCP', 'Jira MCP'],
    howToZh: '1. 配置 Twilio 电话号码\n2. 连接日历、Jira 等工具 MCP\n3. 拨打配置的号码\n4. 语音描述需求（如"今天有什么会议？"）\n5. 代理语音回答',
    howToEn: '1. Configure Twilio phone number\n2. Connect calendar, Jira and other MCPs\n3. Call the configured number\n4. Describe needs by voice (e.g. "What meetings today?")\n5. Agent responds by voice',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/phone-based-personal-assistant.md',
    tags: ['电话', '语音助手', '移动端']
  },
  {
    id: 'inbox-declutter',
    nameZh: '收件箱智能整理',
    nameEn: 'Inbox De-clutter',
    category: 'productivity',
    descZh: '自动汇总订阅邮件中的 Newsletter，以摘要形式发送给你，告别邮件轰炸。',
    descEn: 'Summarize Newsletters and send you a digest as an email.',
    skillsZh: ['邮件 MCP', '内容摘要', '定时任务'],
    skillsEn: ['Email MCP', 'Content Summary', 'Scheduled Tasks'],
    howToZh: '1. 连接邮件账户 MCP\n2. 配置 Newsletter 识别规则\n3. 设置每日/每周摘要时间\n4. 代理自动汇总并发送精华摘要\n5. 原始邮件自动归档',
    howToEn: '1. Connect email account MCP\n2. Configure newsletter identification rules\n3. Set daily/weekly digest schedule\n4. Agent auto-summarizes and sends digest\n5. Original emails auto-archived',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/inbox-declutter.md',
    tags: ['邮件', '整理', '摘要']
  },
  {
    id: 'personal-crm',
    nameZh: '个人 CRM 系统',
    nameEn: 'Personal CRM',
    category: 'productivity',
    descZh: '自动从邮件和日历中发现并追踪联系人，支持自然语言查询，构建你的个人关系网络。',
    descEn: 'Automatically discover and track contacts from your email and calendar, with natural language queries.',
    skillsZh: ['邮件 MCP', '日历 MCP', '数据库存储', '自然语言查询'],
    skillsEn: ['Email MCP', 'Calendar MCP', 'Database Storage', 'Natural Language Query'],
    howToZh: '1. 连接邮件和日历 MCP\n2. 代理自动提取联系人信息\n3. 建立联系人数据库（互动历史、标签）\n4. 用自然语言查询（如"上周和谁开过会？"）\n5. 定期更新联系人状态',
    howToEn: '1. Connect email and calendar MCPs\n2. Agent auto-extracts contact info\n3. Build contact database (interaction history, tags)\n4. Query in natural language (e.g. "Who did I meet last week?")\n5. Periodically update contact status',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/personal-crm.md',
    tags: ['CRM', '联系人管理', '自动化']
  },
  {
    id: 'health-symptom-tracker',
    nameZh: '健康与症状追踪器',
    nameEn: 'Health & Symptom Tracker',
    category: 'productivity',
    descZh: '追踪饮食摄入和症状以识别触发因素，配合定时提醒进行健康检查。',
    descEn: 'Track food intake and symptoms to identify triggers, with scheduled check-in reminders.',
    skillsZh: ['消息推送 MCP', '数据存储', '模式识别', '定时提醒'],
    skillsEn: ['Message Push MCP', 'Data Storage', 'Pattern Recognition', 'Scheduled Reminders'],
    howToZh: '1. 设置每日饮食和症状记录提醒\n2. 通过对话记录饮食和症状\n3. 代理分析数据识别关联模式\n4. 生成健康报告和建议\n5. 追踪长期健康趋势',
    howToEn: '1. Set daily food and symptom logging reminders\n2. Log diet and symptoms via conversation\n3. Agent analyzes data to identify patterns\n4. Generate health reports and suggestions\n5. Track long-term health trends',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/health-symptom-tracker.md',
    tags: ['健康', '追踪', '数据分析']
  },
  {
    id: 'multi-channel-assistant',
    nameZh: '多渠道个人助手',
    nameEn: 'Multi-Channel Personal Assistant',
    category: 'productivity',
    descZh: '通过单一 AI 助手跨 Telegram、Slack、邮件和日历路由任务，统一管理所有工作渠道。',
    descEn: 'Route tasks across Telegram, Slack, email, and calendar from a single AI assistant.',
    skillsZh: ['Telegram MCP', 'Slack MCP', '邮件 MCP', '日历 MCP'],
    skillsEn: ['Telegram MCP', 'Slack MCP', 'Email MCP', 'Calendar MCP'],
    howToZh: '1. 连接所有通信渠道 MCP\n2. 配置任务路由规则\n3. 在任意渠道发送指令\n4. 代理自动路由到正确渠道执行\n5. 统一收件箱查看所有消息',
    howToEn: '1. Connect all communication channel MCPs\n2. Configure task routing rules\n3. Send commands from any channel\n4. Agent auto-routes to correct channel\n5. Unified inbox for all messages',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/multi-channel-assistant.md',
    tags: ['多渠道', '统一助手', '任务路由']
  },
  {
    id: 'project-state-management',
    nameZh: '项目状态管理',
    nameEn: 'Project State Management',
    category: 'productivity',
    descZh: '事件驱动的项目追踪，自动捕获上下文，替代静态看板，实现动态项目状态管理。',
    descEn: 'Event-driven project tracking with automatic context capture, replacing static Kanban boards.',
    skillsZh: ['文件系统 MCP', '事件驱动', '状态机', '通知推送'],
    skillsEn: ['Filesystem MCP', 'Event-Driven', 'State Machine', 'Notification Push'],
    howToZh: '1. 定义项目状态模型（待办/进行中/完成）\n2. 配置事件触发器（代码提交、PR 合并等）\n3. 代理自动更新项目状态\n4. 捕获每次状态变更的上下文\n5. 生成项目进度报告',
    howToEn: '1. Define project state model (todo/in-progress/done)\n2. Configure event triggers (commits, PR merges, etc.)\n3. Agent auto-updates project state\n4. Capture context for each state change\n5. Generate project progress reports',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/project-state-management.md',
    tags: ['项目管理', '状态追踪', '自动化']
  },
  {
    id: 'dynamic-dashboard',
    nameZh: '动态实时仪表盘',
    nameEn: 'Dynamic Dashboard',
    category: 'productivity',
    descZh: '并行从 API、数据库和社交媒体获取数据，构建实时动态仪表盘。',
    descEn: 'Real-time dashboard with parallel data fetching from APIs, databases, and social media.',
    skillsZh: ['多源 API', '并行数据获取', '数据可视化', '实时更新'],
    skillsEn: ['Multi-source API', 'Parallel Data Fetching', 'Data Visualization', 'Real-time Updates'],
    howToZh: '1. 配置数据源（API/数据库/社交媒体）\n2. 定义仪表盘布局和指标\n3. 代理并行获取所有数据源\n4. 实时渲染仪表盘\n5. 设置自动刷新间隔',
    howToEn: '1. Configure data sources (API/database/social media)\n2. Define dashboard layout and metrics\n3. Agent fetches all sources in parallel\n4. Render dashboard in real-time\n5. Set auto-refresh interval',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/dynamic-dashboard.md',
    tags: ['仪表盘', '实时数据', '可视化']
  },
  {
    id: 'todoist-task-manager',
    nameZh: 'Todoist 任务透明管理',
    nameEn: 'Todoist Task Manager',
    category: 'productivity',
    descZh: '通过将推理过程和进度日志同步到 Todoist，最大化代理工作透明度。',
    descEn: 'Maximize agent transparency by syncing reasoning and progress logs to Todoist.',
    skillsZh: ['Todoist MCP', '任务同步', '进度追踪', '透明度'],
    skillsEn: ['Todoist MCP', 'Task Sync', 'Progress Tracking', 'Transparency'],
    howToZh: '1. 连接 Todoist MCP\n2. 代理执行任务时自动创建 Todoist 任务\n3. 每个步骤更新任务状态和备注\n4. 推理过程记录为子任务\n5. 完成后生成执行报告',
    howToEn: '1. Connect Todoist MCP\n2. Agent auto-creates Todoist tasks while working\n3. Update task status and notes at each step\n4. Reasoning process logged as subtasks\n5. Generate execution report on completion',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/todoist-task-manager.md',
    tags: ['Todoist', '任务管理', '透明度']
  },
  {
    id: 'family-calendar-household-assistant',
    nameZh: '家庭日历与家务助手',
    nameEn: 'Family Calendar & Household Assistant',
    category: 'productivity',
    descZh: '聚合所有家庭成员日历生成晨报，监控消息中的预约信息，管理家庭库存。',
    descEn: 'Aggregate all family calendars into a morning briefing, monitor messages for appointments, and manage household inventory.',
    skillsZh: ['日历 MCP', '消息监控', '库存管理', '家庭协作'],
    skillsEn: ['Calendar MCP', 'Message Monitoring', 'Inventory Management', 'Family Collaboration'],
    howToZh: '1. 连接所有家庭成员的日历\n2. 每天早晨生成家庭日程摘要\n3. 监控消息中的预约和提醒\n4. 追踪家庭物品库存\n5. 自动生成购物清单',
    howToEn: '1. Connect all family member calendars\n2. Generate family schedule summary each morning\n3. Monitor messages for appointments and reminders\n4. Track household inventory\n5. Auto-generate shopping lists',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/family-calendar-household-assistant.md',
    tags: ['家庭', '日历', '家务管理']
  },
  {
    id: 'multi-agent-team',
    nameZh: '多智能体专业团队',
    nameEn: 'Multi-Agent Specialized Team',
    category: 'productivity',
    descZh: '通过单一 Telegram 聊天运行多个专业代理（战略、开发、营销、商业），作为协调团队协同工作。',
    descEn: 'Run multiple specialized agents (strategy, dev, marketing, business) as a coordinated team via a single Telegram chat.',
    skillsZh: ['Telegram MCP', '多智能体', '角色分工', '团队协作'],
    skillsEn: ['Telegram MCP', 'Multi-Agent', 'Role Division', 'Team Collaboration'],
    howToZh: '1. 创建 Telegram 群组\n2. 配置各专业代理（战略/开发/营销/商业）\n3. 在群组中发布任务\n4. 各代理根据专长认领并执行\n5. 协调代理汇总结果',
    howToEn: '1. Create Telegram group\n2. Configure specialized agents (strategy/dev/marketing/business)\n3. Post tasks in the group\n4. Agents claim and execute based on expertise\n5. Coordinator agent aggregates results',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/multi-agent-team.md',
    tags: ['多智能体', 'Telegram', '团队协作']
  },
  {
    id: 'aionui-cowork-desktop',
    nameZh: 'OpenClaw 桌面协作工作台',
    nameEn: 'OpenClaw as Desktop Cowork',
    category: 'productivity',
    descZh: '将 OpenClaw 用作桌面协作应用——统一 UI、多智能体、一次配置 MCP，支持 WebUI/Telegram/Lark/钉钉。OpenClaw 宕机时可通过 Telegram 或 WebUI 远程修复。',
    descEn: 'Use OpenClaw as a desktop Cowork app — unified UI, multi-agent, MCP once, WebUI/Telegram/Lark/DingTalk. Fix it remotely via Telegram or WebUI when down.',
    skillsZh: ['桌面 UI', '多智能体', 'MCP 统一配置', '远程管理'],
    skillsEn: ['Desktop UI', 'Multi-Agent', 'Unified MCP Config', 'Remote Management'],
    howToZh: '1. 安装 OpenClaw 桌面版\n2. 一次性配置所有 MCP 工具\n3. 通过统一 UI 管理多个代理\n4. 配置 Telegram/Lark/钉钉 备用访问\n5. 宕机时远程诊断和修复',
    howToEn: '1. Install OpenClaw desktop version\n2. Configure all MCP tools once\n3. Manage multiple agents via unified UI\n4. Configure Telegram/Lark/DingTalk backup access\n5. Remote diagnose and repair when down',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/aionui-cowork-desktop.md',
    tags: ['桌面应用', '统一工作台', '远程管理']
  },
  {
    id: 'custom-morning-brief',
    nameZh: '定制晨报推送',
    nameEn: 'Custom Morning Brief',
    category: 'productivity',
    descZh: '每天早晨收到完全定制的日报——新闻、任务、内容草稿和 AI 推荐行动，直接发送到你的手机。',
    descEn: 'Get a fully customized daily briefing — news, tasks, content drafts, and AI-recommended actions — texted to you every morning.',
    skillsZh: ['新闻聚合', '日历 MCP', '消息推送', 'AI 推荐'],
    skillsEn: ['News Aggregation', 'Calendar MCP', 'Message Push', 'AI Recommendations'],
    howToZh: '1. 配置新闻源、日历和任务来源\n2. 设置晨报模板和偏好\n3. 每天早晨代理自动聚合信息\n4. 生成个性化晨报\n5. 通过短信/Telegram 推送到手机',
    howToEn: '1. Configure news sources, calendar and task sources\n2. Set morning brief template and preferences\n3. Agent auto-aggregates info each morning\n4. Generate personalized morning brief\n5. Push to phone via SMS/Telegram',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/custom-morning-brief.md',
    tags: ['晨报', '个性化', '定时推送']
  },
  {
    id: 'meeting-notes-action-items',
    nameZh: '自动会议记录与行动项',
    nameEn: 'Automated Meeting Notes & Action Items',
    category: 'productivity',
    descZh: '将会议转录转化为结构化摘要，并自动在 Jira、Linear 或 Todoist 中创建任务，分配给正确的人。',
    descEn: 'Turn meeting transcripts into structured summaries and automatically create tasks in Jira, Linear, or Todoist — assigned to the right person.',
    skillsZh: ['语音转文字', 'Jira MCP', 'Linear MCP', 'Todoist MCP'],
    skillsEn: ['Speech-to-Text', 'Jira MCP', 'Linear MCP', 'Todoist MCP'],
    howToZh: '1. 上传会议录音或转录文本\n2. 代理提取关键决策和行动项\n3. 识别负责人和截止日期\n4. 自动在项目管理工具中创建任务\n5. 发送会议摘要给参与者',
    howToEn: '1. Upload meeting recording or transcript\n2. Agent extracts key decisions and action items\n3. Identify owners and deadlines\n4. Auto-create tasks in project management tools\n5. Send meeting summary to participants',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/meeting-notes-action-items.md',
    tags: ['会议', '行动项', '自动化']
  },
  {
    id: 'habit-tracker-accountability-coach',
    nameZh: '习惯追踪与问责教练',
    nameEn: 'Habit Tracker & Accountability Coach',
    category: 'productivity',
    descZh: '通过 Telegram 或短信进行主动每日打卡，追踪习惯连续天数，根据进度调整语气。',
    descEn: 'Proactive daily check-ins via Telegram or SMS that track habits, maintain streaks, and adapt their tone based on your progress.',
    skillsZh: ['Telegram MCP', '习惯追踪', '连续天数', '自适应语气'],
    skillsEn: ['Telegram MCP', 'Habit Tracking', 'Streak Maintenance', 'Adaptive Tone'],
    howToZh: '1. 定义要追踪的习惯列表\n2. 设置每日打卡提醒时间\n3. 代理主动发送打卡消息\n4. 记录完成情况和连续天数\n5. 根据进度调整鼓励/督促语气',
    howToEn: '1. Define habit list to track\n2. Set daily check-in reminder time\n3. Agent proactively sends check-in messages\n4. Record completion and streaks\n5. Adapt encouraging/motivating tone based on progress',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/habit-tracker-accountability-coach.md',
    tags: ['习惯', '打卡', '问责']
  },
  {
    id: 'second-brain',
    nameZh: '第二大脑',
    nameEn: 'Second Brain',
    category: 'productivity',
    descZh: '向机器人发送任何内容来记忆，然后通过自定义 Next.js 仪表盘搜索所有记忆。',
    descEn: 'Text anything to your bot to remember it, then search through all your memories in a custom Next.js dashboard.',
    skillsZh: ['Telegram MCP', 'Next.js', '向量搜索', '知识存储'],
    skillsEn: ['Telegram MCP', 'Next.js', 'Vector Search', 'Knowledge Storage'],
    howToZh: '1. 向 Telegram 机器人发送任何想记住的内容\n2. 代理自动提取关键信息并存储\n3. 打开 Next.js 仪表盘\n4. 用自然语言搜索记忆\n5. 代理返回相关记忆片段',
    howToEn: '1. Send anything to Telegram bot to remember\n2. Agent auto-extracts key info and stores\n3. Open Next.js dashboard\n4. Search memories in natural language\n5. Agent returns relevant memory fragments',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/second-brain.md',
    tags: ['知识管理', '第二大脑', '搜索']
  },
  {
    id: 'event-guest-confirmation',
    nameZh: '活动嘉宾确认自动化',
    nameEn: 'Event Guest Confirmation',
    category: 'productivity',
    descZh: '逐一致电活动嘉宾确认出席情况，收集备注并汇总报告——通过 AI 语音通话全自动完成。',
    descEn: 'Call a list of event guests one-by-one to confirm attendance, collect notes, and compile a summary — fully automated via AI voice calls.',
    skillsZh: ['Twilio MCP', 'AI 语音通话', '数据收集', '报告生成'],
    skillsEn: ['Twilio MCP', 'AI Voice Calls', 'Data Collection', 'Report Generation'],
    howToZh: '1. 上传嘉宾名单（姓名+电话）\n2. 配置确认话术和问题\n3. 代理自动逐一拨打电话\n4. AI 语音对话收集确认信息\n5. 汇总出席情况报告',
    howToEn: '1. Upload guest list (name + phone)\n2. Configure confirmation script and questions\n3. Agent auto-calls each guest\n4. AI voice conversation collects confirmation\n5. Compile attendance summary report',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/event-guest-confirmation.md',
    tags: ['活动管理', '语音通话', '自动化']
  },
  {
    id: 'phone-call-notifications',
    nameZh: '电话通知系统',
    nameEn: 'Phone Call Notifications',
    category: 'productivity',
    descZh: '将代理的告警转化为真实电话——晨报、价格下跌、紧急邮件——支持双向对话。',
    descEn: 'Turn your agent\'s alerts into real phone calls — morning briefings, price drops, urgent emails — with two-way conversation.',
    skillsZh: ['Twilio MCP', 'AI 语音', '告警触发', '双向对话'],
    skillsEn: ['Twilio MCP', 'AI Voice', 'Alert Triggers', 'Two-way Conversation'],
    howToZh: '1. 配置告警触发条件（价格/邮件/事件）\n2. 连接 Twilio 电话服务\n3. 触发条件满足时自动拨打电话\n4. AI 语音播报告警内容\n5. 支持语音回复进行双向交互',
    howToEn: '1. Configure alert trigger conditions (price/email/event)\n2. Connect Twilio phone service\n3. Auto-call when trigger conditions met\n4. AI voice announces alert content\n5. Support voice reply for two-way interaction',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/phone-call-notifications.md',
    tags: ['电话通知', '告警', '双向对话']
  },
  {
    id: 'local-crm-framework',
    nameZh: '本地 CRM 框架',
    nameEn: 'Local CRM Framework',
    category: 'productivity',
    descZh: '通过 `npx denchclaw` 将 OpenClaw 变成完全本地化的 CRM 和销售自动化平台——DuckDB、浏览器自动化、多视图 UI 和自然语言查询。',
    descEn: 'Turn OpenClaw into a fully local CRM and sales automation platform with `npx denchclaw` — DuckDB, browser automation, multi-view UI, and natural language queries.',
    skillsZh: ['DuckDB', '浏览器自动化', '本地存储', '自然语言查询'],
    skillsEn: ['DuckDB', 'Browser Automation', 'Local Storage', 'Natural Language Query'],
    howToZh: '1. 运行 `npx denchclaw` 初始化本地 CRM\n2. 导入联系人和销售数据\n3. 配置浏览器自动化规则\n4. 用自然语言查询和管理数据\n5. 通过多视图 UI 可视化销售漏斗',
    howToEn: '1. Run `npx denchclaw` to initialize local CRM\n2. Import contacts and sales data\n3. Configure browser automation rules\n4. Query and manage data in natural language\n5. Visualize sales funnel via multi-view UI',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/local-crm-framework.md',
    tags: ['CRM', '本地化', '销售自动化']
  },
  // ── Research & Learning ───────────────────────────────────────────────────
  {
    id: 'earnings-tracker',
    nameZh: 'AI 财报追踪器',
    nameEn: 'AI Earnings Tracker',
    category: 'research',
    descZh: '追踪科技/AI 公司财报，自动生成预览、告警和详细摘要。',
    descEn: 'Track tech/AI earnings reports with automated previews, alerts, and detailed summaries.',
    skillsZh: ['财经数据 MCP', '定时监控', '报告生成', '告警推送'],
    skillsEn: ['Financial Data MCP', 'Scheduled Monitoring', 'Report Generation', 'Alert Push'],
    howToZh: '1. 配置要追踪的公司列表\n2. 设置财报日期监控\n3. 财报发布前自动生成预览分析\n4. 财报发布后生成详细摘要\n5. 推送关键数据告警',
    howToEn: '1. Configure company watchlist\n2. Set up earnings date monitoring\n3. Auto-generate preview analysis before earnings\n4. Generate detailed summary after release\n5. Push key data alerts',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/earnings-tracker.md',
    tags: ['财报', '追踪', '金融分析']
  },
  {
    id: 'knowledge-base-rag',
    nameZh: '个人知识库（RAG）',
    nameEn: 'Personal Knowledge Base (RAG)',
    category: 'research',
    descZh: '通过向对话中投入 URL、推文和文章，构建可搜索的个人知识库。',
    descEn: 'Build a searchable knowledge base by dropping URLs, tweets, and articles into chat.',
    skillsZh: ['向量数据库', 'RAG 检索', 'Web 抓取', '语义搜索'],
    skillsEn: ['Vector Database', 'RAG Retrieval', 'Web Scraping', 'Semantic Search'],
    howToZh: '1. 向对话中粘贴 URL/推文/文章\n2. 代理自动抓取并向量化内容\n3. 存入个人知识库\n4. 用自然语言提问\n5. RAG 检索返回相关内容',
    howToEn: '1. Paste URLs/tweets/articles into chat\n2. Agent auto-scrapes and vectorizes content\n3. Store in personal knowledge base\n4. Ask questions in natural language\n5. RAG retrieval returns relevant content',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/knowledge-base-rag.md',
    tags: ['知识库', 'RAG', '语义搜索']
  },
  {
    id: 'market-research-product-factory',
    nameZh: '市场研究与产品工厂',
    nameEn: 'Market Research & Product Factory',
    category: 'research',
    descZh: '挖掘 Reddit 和 X 上的真实痛点，然后让 OpenClaw 构建解决这些痛点的 MVP。',
    descEn: 'Mine Reddit and X for real pain points, then have OpenClaw build MVPs that solve them.',
    skillsZh: ['Reddit MCP', 'X/Twitter MCP', '痛点分析', 'MVP 构建'],
    skillsEn: ['Reddit MCP', 'X/Twitter MCP', 'Pain Point Analysis', 'MVP Building'],
    howToZh: '1. 配置目标市场关键词\n2. 代理挖掘 Reddit/X 上的用户痛点\n3. 分析和排序痛点优先级\n4. 为高优先级痛点设计 MVP 方案\n5. 自动构建并部署 MVP',
    howToEn: '1. Configure target market keywords\n2. Agent mines Reddit/X for user pain points\n3. Analyze and prioritize pain points\n4. Design MVP for high-priority pain points\n5. Auto-build and deploy MVP',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/market-research-product-factory.md',
    tags: ['市场研究', 'MVP', '痛点挖掘']
  },
  {
    id: 'pre-build-idea-validator',
    nameZh: '构建前创意验证器',
    nameEn: 'Pre-Build Idea Validator',
    category: 'research',
    descZh: '在构建任何新东西之前，自动扫描 GitHub、HN、npm、PyPI 和 Product Hunt——市场拥挤则停止，空白则继续。',
    descEn: 'Automatically scan GitHub, HN, npm, PyPI, and Product Hunt before building — stop if crowded, proceed if open.',
    skillsZh: ['GitHub MCP', 'HN 搜索', 'npm 搜索', 'Product Hunt MCP'],
    skillsEn: ['GitHub MCP', 'HN Search', 'npm Search', 'Product Hunt MCP'],
    howToZh: '1. 描述你的创意\n2. 代理自动搜索 GitHub/HN/npm/PyPI/PH\n3. 分析竞品数量和质量\n4. 评估市场空间\n5. 给出"继续/停止"建议',
    howToEn: '1. Describe your idea\n2. Agent auto-searches GitHub/HN/npm/PyPI/PH\n3. Analyze competitor count and quality\n4. Evaluate market space\n5. Give "proceed/stop" recommendation',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/pre-build-idea-validator.md',
    tags: ['创意验证', '市场分析', '竞品调研']
  },
  {
    id: 'semantic-memory-search',
    nameZh: '语义记忆搜索',
    nameEn: 'Semantic Memory Search',
    category: 'research',
    descZh: '为 OpenClaw Markdown 记忆文件添加向量驱动的语义搜索，支持混合检索和自动同步。',
    descEn: 'Add vector-powered semantic search to your OpenClaw markdown memory files with hybrid retrieval and auto-sync.',
    skillsZh: ['向量数据库', '语义搜索', 'Markdown 解析', '混合检索'],
    skillsEn: ['Vector Database', 'Semantic Search', 'Markdown Parsing', 'Hybrid Retrieval'],
    howToZh: '1. 配置向量数据库（如 Chroma/Qdrant）\n2. 自动索引所有 Markdown 记忆文件\n3. 设置文件变更自动同步\n4. 用语义查询搜索记忆\n5. 混合检索（语义+关键词）返回最相关结果',
    howToEn: '1. Configure vector database (e.g. Chroma/Qdrant)\n2. Auto-index all Markdown memory files\n3. Set up auto-sync on file changes\n4. Search memories with semantic queries\n5. Hybrid retrieval (semantic+keyword) returns most relevant results',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/semantic-memory-search.md',
    tags: ['语义搜索', '向量数据库', '记忆管理']
  },
  {
    id: 'arxiv-paper-reader',
    nameZh: 'arXiv 论文阅读助手',
    nameEn: 'arXiv Paper Reader',
    category: 'research',
    descZh: '对话式阅读和分析 arXiv 论文——按 ID 获取、浏览章节、比较摘要、获取 AI 摘要。',
    descEn: 'Read and analyze arXiv papers conversationally — fetch by ID, browse sections, compare abstracts, and get AI summaries.',
    skillsZh: ['arXiv MCP', '论文解析', 'PDF 处理', '摘要生成'],
    skillsEn: ['arXiv MCP', 'Paper Parsing', 'PDF Processing', 'Summary Generation'],
    howToZh: '1. 提供 arXiv 论文 ID 或关键词\n2. 代理自动获取论文内容\n3. 对话式浏览各章节\n4. 生成中文摘要和关键点\n5. 与其他论文进行比较分析',
    howToEn: '1. Provide arXiv paper ID or keywords\n2. Agent auto-fetches paper content\n3. Browse sections conversationally\n4. Generate summary and key points\n5. Compare with other papers',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/arxiv-paper-reader.md',
    tags: ['论文', 'arXiv', '学术研究']
  },
  {
    id: 'latex-paper-writing',
    nameZh: 'LaTeX 论文写作助手',
    nameEn: 'LaTeX Paper Writing',
    category: 'research',
    descZh: '对话式写作和编译 LaTeX 论文，即时 PDF 预览——无需本地 TeX 安装。',
    descEn: 'Write and compile LaTeX papers conversationally with instant PDF preview — no local TeX installation needed.',
    skillsZh: ['LaTeX 编译', 'PDF 预览', '云端 TeX', '学术写作'],
    skillsEn: ['LaTeX Compilation', 'PDF Preview', 'Cloud TeX', 'Academic Writing'],
    howToZh: '1. 描述论文结构和内容\n2. 代理生成 LaTeX 源码\n3. 云端编译并预览 PDF\n4. 对话式修改和完善\n5. 导出最终 PDF',
    howToEn: '1. Describe paper structure and content\n2. Agent generates LaTeX source code\n3. Cloud compile and preview PDF\n4. Conversationally revise and refine\n5. Export final PDF',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/latex-paper-writing.md',
    tags: ['LaTeX', '论文写作', '学术']
  },
  {
    id: 'hf-papers-research-discovery',
    nameZh: 'HF 论文研究发现',
    nameEn: 'HF Papers Research Discovery',
    category: 'research',
    descZh: '发现 Hugging Face 上的热门 ML 论文，按点赞数分类，通过 arXiv 深度阅读——全程对话式操作。',
    descEn: 'Discover trending ML papers on Hugging Face, triage by upvotes, and deep-read via arXiv — all conversationally.',
    skillsZh: ['Hugging Face MCP', 'arXiv MCP', '论文排名', '趋势分析'],
    skillsEn: ['Hugging Face MCP', 'arXiv MCP', 'Paper Ranking', 'Trend Analysis'],
    howToZh: '1. 连接 Hugging Face Papers MCP\n2. 获取今日/本周热门论文\n3. 按点赞数和相关性排序\n4. 选择感兴趣的论文深度阅读\n5. 生成研究趋势报告',
    howToEn: '1. Connect Hugging Face Papers MCP\n2. Fetch today/this week trending papers\n3. Sort by upvotes and relevance\n4. Deep-read selected papers\n5. Generate research trend report',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/hf-papers-research-discovery.md',
    tags: ['机器学习', 'Hugging Face', '论文发现']
  },
  // ── Finance & Trading ─────────────────────────────────────────────────────
  {
    id: 'polymarket-autopilot',
    nameZh: 'Polymarket 自动驾驶',
    nameEn: 'Polymarket Autopilot',
    category: 'finance',
    descZh: '在预测市场上进行自动化模拟交易，包含回测、策略分析和每日绩效报告。',
    descEn: 'Automated paper trading on prediction markets with backtesting, strategy analysis, and daily performance reports.',
    skillsZh: ['Polymarket API', '策略回测', '风险管理', '绩效报告'],
    skillsEn: ['Polymarket API', 'Strategy Backtesting', 'Risk Management', 'Performance Reports'],
    howToZh: '1. 连接 Polymarket API\n2. 定义交易策略和风险参数\n3. 在模拟模式下运行策略\n4. 每日生成绩效报告\n5. 回测历史数据优化策略',
    howToEn: '1. Connect Polymarket API\n2. Define trading strategy and risk parameters\n3. Run strategy in paper trading mode\n4. Generate daily performance reports\n5. Backtest historical data to optimize strategy',
    githubUrl: 'https://github.com/hesamsheikh/awesome-openclaw-usecases/blob/main/usecases/polymarket-autopilot.md',
    tags: ['预测市场', '自动交易', '回测']
  }
];

// Export for use in other scripts
if (typeof module !== 'undefined') {
  module.exports = { SITE, CATEGORIES, CASES };
}
